version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
